In [1]:
import pandas as pd
import sys
sys.path.append('../core')
from ReactChemChecker import canonicalize_reaction

c:\Anaconda\lib\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
c:\Anaconda\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.4' currently installed).
  from pandas.core import (

In [2]:
cofactor_list = pd.read_pickle("acquired_data/Cofactor_list.pkl")
rxn_smiles_data = pd.read_csv("acquired_data/06182025_rhea-reaction-smiles.tsv", 
                         delimiter="\t", names=['RHEA_ID', 'rxn_smiles'], engine='python')

In [3]:
len(cofactor_list)

60

In [4]:
cofactor_list

['[Fe+2]',
 'CC(C)=CCC/C(C)=C/CC/C(C)=C/COP(=O)([O-])OP(=O)([O-])[O-]',
 'CC(C)(COP(=O)([O-])OP(=O)([O-])OC[C@H]1O[C@@H](n2cnc3c(N)ncnc32)[C@H](O)[C@@H]1OP(=O)([O-])[O-])[C@@H](O)C(=O)NCCC(=O)NCCSC(=O)CC(=O)[O-]',
 'O=C([O-])CCC(=O)C(=O)[O-]',
 'O=c1ccn([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])O[C@H]3O[C@H](CO)[C@@H](O)[C@H](O)[C@H]3O)[C@@H](O)[C@H]2O)c(=O)[nH]1',
 'O=C=O',
 'NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](O)[C@@H]3O)[C@@H](O)[C@H]2O)C=CC1',
 'O=C([O-])CCC(=O)[O-]',
 'C',
 'CI',
 'O=c1ccn([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])[O-])[C@@H](O)[C@H]2O)c(=O)[nH]1',
 'O=P([O-])([O-])OP(=O)([O-])O',
 'S1[Fe]S[Fe+]1',
 'OCC(O)CO',
 'Cc1cc2nc3c(=O)[n-]c(=O)nc-3n(C[C@H](O)[C@H](O)[C@H](O)COP(=O)([O-])[O-])c2cc1C',
 'NO',
 '[Fe+3]',
 'NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)c1',
 'CCCCC/C=C\\C/C=C\\C/C=C\\C/C=C\\CCCC(=O)[O-]',
 'CCCCCCCC/C=C\\CCCCCCCC(=O)[O-]',
 'OO',
 'CCCCCCCCCCCCCCCC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)([O-])OP(=O)([O-])OC[C@H]1O[C@@H](n2cnc3c(N)ncnc32)[C@H](O)[C@@H]1OP(=O)([O-])[O-]',
 'C[C@H]([NH3+])C(=O)[O-]',
 'CCCCCCCCCCCCCCCC(=O)[O-]',
 'NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)C=CC1',
 '[NH3+][C@@H](CCC(=O)[O-])C(=O)[O-]',
 'Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)([O-])[O-])[C@@H](O)[C@H]1O',
 'Cc1cc2c(cc1C)N(C[C@H](O)[C@H](O)[C@H](O)COP(=O)([O-])OP(=O)([O-])OC[C@H]1O[C@@H](n3cnc4c(N)ncnc43)[C@H](O)[C@@H]1O)c1[nH]c(=O)[nH]c(=O)c1N2',
 'CCCCCCCCCCCCCCCC(=O)OC[C@@H](O)COP(=O)([O-])OCC[N+](C)(C)C',
 'II',
 '[NH3+]CC(=O)[O-]',
 'O=O',
 'NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](O)[C@@H]3O)[C@@H](O)[C@H]2O)c1',
 'C[S+](CC[C@H]([NH3+])C(=O)[O-])C[C@H]1O[C@@H](n2cnc3c(N)ncnc32)[C@H](O)[C@@H]1O',
 'Cc1cc2c(cc1C)N(C[C@H](O)[C@H](O)[C@H](O)COP(=O)([O-])[O-])c1[nH]c(=O)[nH]c(=O)c1N2',
 '[NH3+][C@@H](CCC(=O)N[C@@H](CS)C(=O)NCC(=O)[O-])C(=O)[O-]',
 'Cc1cc2nc3c(=O)[n-]c(=O)nc-3n(C[C@H](O)[C@H](O)[C@H](O)COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](O)[C@@H]3O)c2cc1C',
 'S',
 'CO',
 'Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)([O-])OP(=O)([O-])OP(=O)([O-])[O-])[C@@H](O)[C@H]1O',
 'Nc1nc2c(ncn2[C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])[O-])[C@@H](O)[C@H]2O)c(=O)[nH]1',
 'Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)([O-])OP(=O)([O-])[O-])[C@@H](O)[C@H]1O',
 'Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)([O-])[O-])[C@@H](OP(=O)([O-])[O-])[C@H]1O',
 'O=P([O-])([O-])O',
 'CCCCCCCC/C=C\\CCCCCCCC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)([O-])OP(=O)([O-])OC[C@H]1O[C@@H](n2cnc3c(N)ncnc32)[C@H](O)[C@@H]1OP(=O)([O-])[O-]',
 'CC(C)(COP(=O)([O-])OP(=O)([O-])OC[C@H]1O[C@@H](n2cnc3c(N)ncnc32)[C@H](O)[C@@H]1OP(=O)([O-])[O-])[C@@H](O)C(=O)NCCC(=O)NCCS',
 'C=O',
 'S1[Fe+]S[Fe+]1',
 '[NH4+]',
 'O=C[O-]',
 'O=CC(=O)[O-]',
 'CC(=O)[O-]',
 'OC[C@H]1OC(O)[C@H](O)[C@@H](O)[C@@H]1O',
 'Nc1ncnc2c1ncn2[C@@H]1O[C@H](CSCC[C@H]([NH3+])C(=O)[O-])[C@@H](O)[C@H]1O',
 'NN',
 'O=C([O-])[C@H]1O[C@H](OP(=O)([O-])OP(=O)([O-])OC[C@H]2O[C@@H](n3ccc(=O)[nH]c3=O)[C@H](O)[C@@H]2O)[C@H](O)[C@@H](O)[C@@H]1O',
 'O',
 'CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)([O-])OP(=O)([O-])OC[C@H]1O[C@@H](n2cnc3c(N)ncnc32)[C@H](O)[C@@H]1OP(=O)([O-])[O-]',
 'CS',
 'CC(=O)C(=O)[O-]']

In [59]:
cofactor_by_id = {
    'id': [],
    'cofactors_left': [],
    'cofactors_right': []
}    

for idx, row in rxn_smiles_data.iterrows():
    _id = row['RHEA_ID']
    rxn_smiles = canonicalize_reaction(row['rxn_smiles'])

    cofactor_by_id['id'].append(_id)

    cft_left = []
    cft_right = []
    rct, prd = rxn_smiles.split(">>")
    for item in rct.split('.'):
        if item in cofactor_list:
            cft_left.append(item)

    if cft_left:
        cofactor_by_id['cofactors_left'].append('.'.join(cft_left))
    else:
        cofactor_by_id['cofactors_left'].append("nan")

    for item in prd.split('.'):
        if item in cofactor_list:
            cft_right.append(item)

    if cft_right:
        cofactor_by_id['cofactors_right'].append('.'.join(cft_right))
    else:
        cofactor_by_id['cofactors_right'].append("nan")

In [60]:
for idx in range(0, 25):
    print(cofactor_by_id['id'][idx])
    print(cofactor_by_id['cofactors_left'][idx])
    print(cofactor_by_id['cofactors_right'][idx])
    print("--")

10001
O
[NH4+]
--
10002
[NH4+]
O
--
10005
nan
nan
--
10006
nan
nan
--
10009
nan
O
--
10010
O
nan
--
10013
O.O=O
OO
--
10014
OO
O.O=O
--
10017
O
nan
--
10018
nan
O
--
10021
NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)c1.O
NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)C=CC1.[NH3+][C@@H](CCC(=O)[O-])C(=O)[O-]
--
10022
NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)C=CC1.[NH3+][C@@H](CCC(=O)[O-])C(=O)[O-]
NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)c1.O
--
10025
C[S+](CC[C@H]([NH3+])C(=O)[O-])C[C@H]1O[C@@H](n2cnc3c(N)ncnc32)[C@H](O)[C@@H]1O
Nc1ncnc2c1ncn2[C@@H]1O[C@H](CSCC[C@H]([NH3+])C(=O)[O-])[C@@H](O)[C@H]1O
--
10026
Nc1ncnc2c1ncn2[C@@H]1O[C@H](CSCC[C@H]([NH3+])C(=O)[O-])[C@@H](O)[C@H]1O
C[S+](CC[C@H]([NH3+])C(=O)[O-])C[C@H]1O[C@@H](n2cnc3c(N)ncnc32)[C@H](O)[C@@H]1O
--
10029
O.O=O
O=C([O-])CCC(=O)C(=O)[O-].OO.[NH4+]
--
10030
O=C([O-])CCC(=O)C(=O)[O-].OO.[NH4+]
O.O=O
--
10033
O
[NH4+]
--
10034
[NH4+]
O
--
10037
O=O
OO
--
10038
OO
O=O
--
10041
Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)([O-])[O-])[C@@H](OP(=O)([O-])[O-])[C@H]1O.O
Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)([O-])[O-])[C@@H](O)[C@H]1O.O=P([O-])([O-])O
--
10042
Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)([O-])[O-])[C@@H](O)[C@H]1O.O=P([O-])([O-])O
Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)([O-])[O-])[C@@H](OP(=O)([O-])[O-])[C@H]1O.O
--
10045
NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](O)[C@@H]3O)[C@@H](O)[C@H]2O)c1
NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](O)[C@@H]3O)[C@@H](O)[C@H]2O)C=CC1
--
10046
NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](O)[C@@H]3O)[C@@H](O)[C@H]2O)C=CC1
NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](O)[C@@H]3O)[C@@H](O)[C@H]2O)c1
--
10049
CS
CC(=O)[O-]
--

In [61]:
df = pd.DataFrame(cofactor_by_id)

In [62]:
df.to_csv("../data/cofactor_by_id.csv", index=False)

In [ ]:
def add_missing_components(rhea_id=None, precursors=None, target=None, cofactors=None, debug=False):

    matching_row = cofactors[cofactors['id'] == rhea_id]
    cofactors_right = matching_row['cofactors_right'].iloc[0]
    cofactors_left = matching_row['cofactors_left'].iloc[0]
    
    # Build left side (from precursors)
    left_molecules = precursors
    if not pd.isna(cofactors_left):
        for cofactor in cofactors_left.split('.'):
            if cofactor not in precursors and cofactor != "nan":
                left_molecules.append(cofactor)
    
    
    # Build right side (from target)
    right_molecules = [target]
    if not pd.isna(cofactors_right):
        for cofactor in cofactors_right.split('.'):
            if cofactor != target and cofactor != "nan":
                 right_molecules.append(cofactor)
                    
    # fully assembled reaction
    full_reaction = '.'.join(left_molecules) + '>>' + '.'.join(right_molecules)
    
    if debug:
        print(full_reaction)

    return full_reaction

In [ ]:
rhea_id = 10029
precursors = ['[NH3+][C@H](CCC(=O)[O-])C(=O)[O-]']
target = 'O=C([O-])CCC(=O)C(=O)[O-]'
add_missing_components(rhea_id=rhea_id, precursors=precursors, target=target, cofactors=df, debug=True)

[NH3+][C@H](CCC(=O)[O-])C(=O)[O-].O.O=O>>O=C([O-])CCC(=O)C(=O)[O-].OO.[NH4+]

'[NH3+][C@H](CCC(=O)[O-])C(=O)[O-].O.O=O>>O=C([O-])CCC(=O)C(=O)[O-].OO.[NH4+]'

In [ ]:
rhea_id = 10005
precursors = ['[NH3+][C@H](CCC(=O)[O-])C(=O)[O-]']
target = 'O=C([O-])CCC(=O)C(=O)[O-]'
add_missing_components(rhea_id=rhea_id, precursors=precursors, target=target, cofactors=df, debug=True)

[NH3+][C@H](CCC(=O)[O-])C(=O)[O-]>>O=C([O-])CCC(=O)C(=O)[O-]

'[NH3+][C@H](CCC(=O)[O-])C(=O)[O-]>>O=C([O-])CCC(=O)C(=O)[O-]'

### New strategy

In [3]:
rdenzyme_file = pd.read_pickle("../data/rhea_atom_mapped_for_jx_cache.pkl")

In [10]:
len(rdenzyme_file)

16648

In [5]:
rdenzyme_file.columns

Index(['id', 'prod_smiles', 'rxn_smiles', 'atom mapped smiles-input',
       'not atom mapped smiles-input', 'prod_fp', 'reaction_smarts',
       'rcts_ref_fp'],
      dtype='object')

In [25]:
# First, check for duplicates
already_seen = []
duplicate = []

for idx, row in rdenzyme_file.iterrows():
    _id = str(row['id'])

    if _id in already_seen:
        duplicate.append(_id)
    else:
        already_seen.append(_id)

In [26]:
len(already_seen) + len(duplicate)

16648

In [17]:
import rdkit.Chem as Chem

def remove_atom_map(smi):

    react, prod = smi.split('>>')

    react_mol = Chem.MolFromSmiles(react)
    prod_mol = Chem.MolFromSmiles(prod)

    for atom in react_mol.GetAtoms():
        atom.SetAtomMapNum(0)

    for atom in prod_mol.GetAtoms():
        atom.SetAtomMapNum(0)

    return Chem.MolToSmiles(react_mol)+'>>'+Chem.MolToSmiles(prod_mol)

In [36]:
missing_components = {
    'id': [],
    'missing_comp_left': [],
    'missing_comp_right': []
}

duplicate_counters = {}

for idx, row in rdenzyme_file.iterrows():
    _id = row['id']
    template_reaction = canonicalize_reaction(remove_atom_map(row['rxn_smiles']))
    full_rhea_reaction = canonicalize_reaction(row['not atom mapped smiles-input'])

    str_id = str(_id)
    if str_id in duplicate:
        count = duplicate_counters.get(str_id, 0)
        missing_components['id'].append(f"{str_id}-{count}")
        duplicate_counters[str_id] = count + 1
    else:
        missing_components['id'].append(str_id)

    rct_temp, prd_temp = template_reaction.split(">>")
    rct_full, prd_full = full_rhea_reaction.split(">>")

    rct_temp_list = rct_temp.split('.')
    prd_temp_list = prd_temp.split('.')

    comp_left = [item for item in rct_full.split('.') if item not in rct_temp_list]
    missing_components['missing_comp_left'].append('.'.join(comp_left) if comp_left else "nan")

    comp_right = [item for item in prd_full.split('.') if item not in prd_temp_list]
    missing_components['missing_comp_right'].append('.'.join(comp_right) if comp_right else "nan")

In [37]:
for idx in range(0, 25):
    print(missing_components['id'][idx])
    print(missing_components['missing_comp_left'][idx])
    print(missing_components['missing_comp_right'][idx])
    print("--")

20342
nan
O=c1ccn([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])[O-])[C@@H](O)[C@H]2O)c(=O)[nH]1.[H+]
--
24762
NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](O)[C@@H]3O)[C@@H](O)[C@H]2O)c1
NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](O)[C@@H]3O)[C@@H](O)[C@H]2O)C=CC1.[H+]
--
23757
O=O
OO.[H+]
--
23854
[H+].[H+]
O=O
--
15154
nan
O=c1ccn([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])[O-])[C@@H](O)[C@H]2O)c(=O)[nH]1.[H+]
--
50538
nan
nan
--
50174
nan
O=O
--
37517
nan
CCCCCCCCCCCCCCCC(=O)OC[C@@H](O)COP(=O)([O-])OCC[N+](C)(C)C
--
19366
nan
Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)([O-])OP(=O)([O-])[O-])[C@@H](O)[C@H]1O.[H+]
--
57589
Cc1cc2c(cc1C)N(C[C@H](O)[C@H](O)[C@H](O)COP(=O)([O-])[O-])c1[nH]c(=O)[nH]c(=O)c1N2
Cc1cc2nc3c(=O)[n-]c(=O)nc-3n(C[C@H](O)[C@H](O)[C@H](O)COP(=O)([O-])[O-])c2cc1C.O.[H+]
--
51414
nan
O=O
--
55009
NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)C=CC1
NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)c1.O
--
10365
nan
CC(C)(COP(=O)([O-])OP(=O)([O-])OC[C@H]1O[C@@H](n2cnc3c(N)ncnc32)[C@H](O)[C@@H]1OP(=O)([O-])[O-])[C@@H](O)C(=O)NCCC(=O)NCCS.[H+]
--
37324
O
[NH3+]CC(=O)[O-]
--
41156
nan
CCCCCCCCCCCCCCCC(=O)OC[C@@H](O)COP(=O)([O-])OCC[N+](C)(C)C.[H+]
--
13598-0
O
NC(N)=O
--
13598-1
nan
NC(=[NH2+])NCCCC[NH3+]
--
59905
NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)c1
NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)C=CC1.[H+].[H+]
--
25585
nan
nan
--
12177
nan
Nc1ncnc2c1ncn2[C@@H]1O[C@H](CSCC[C@H]([NH3+])C(=O)[O-])[C@@H](O)[C@H]1O.[H+]
--
17383
nan
nan
--
40856
Cc1cc2nc3c(=O)[n-]c(=O)nc-3n(C[C@H](O)[C@H](O)[C@H](O)COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](O)[C@@H]3O)c2cc1C.[H+]
Cc1cc2c(cc1C)N(C[C@H](O)[C@H](O)[C@H](O)COP(=O)([O-])OP(=O)([O-])OC[C@H]1O[C@@H](n3cnc4c(N)ncnc43)[C@H](O)[C@@H]1O)c1[nH]c(=O)[nH]c(=O)c1N2
--
29365
nan
O
--
21221
nan
[H+]
--
60974
NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](O)[C@@H]3O)[C@@H](O)[C@H]2O)C=CC1.[H+]
NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](O)[C@@H]3O)[C@@H](O)[C@H]2O)c1
--

In [38]:
df = pd.DataFrame(missing_components)

In [39]:
df.to_csv("../data/missing_rhea_components.csv", index=False)

In [41]:
rdenzyme_file

,id,prod_smiles,rxn_smiles,atom mapped smiles-input,not atom mapped smiles-input,prod_fp,reaction_smarts,rcts_ref_fp
0,20342,O=P([O-])([O-])OC[C@H](O)CO[C@H]1O[C@H](CO)[C@...,O=c1ccn([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-]...,[[O:11]=[c:12]1[cH:13][cH:14][n:15]([C@@H:16]2...,O=C1C=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-...,<rdkit.DataStructs.cDataStructs.UIntSparseIntV...,([#8:2]-[C@@H;D3;+0:1](-[C:3])-[O;H0;D2;+0:5]-...,<rdkit.DataStructs.cDataStructs.UIntSparseIntV...
1,24762,[NH3+][C@@H](Cc1ccc(O)c(O)c1)C(=O)[O-],[NH4+:45].[O:46]=[C:47]([O-:48])[CH2:49][CH2:5...,[[NH2:1][C:2](=[O:3])[c:4]1[cH:5][cH:6][cH:7][...,NC(=O)C1=CC=C[N+]([C@@H]2O[C@H](COP(=O)([O-])O...,<rdkit.DataStructs.cDataStructs.UIntSparseIntV...,([C:1]-[C@H;D3;+0:2](-[NH3+;D1:6])-[C:3](-[O;-...,<rdkit.DataStructs.cDataStructs.UIntSparseIntV...
2,23757,O=C1O[C@H](CO)C([O-])=C1O,[O:1]=[C:2]1[O:3][C@H:4]([CH2:5][OH:6])[C@@H:7...,[[O:11]=[O:12].[O:1]=[C:2]1[O:3][C@H:4]([CH2:5...,O=C1O[C@H](CO)[C@@H](O)[C@@H]1O.O=O>>O=C1O[C@H...,<rdkit.DataStructs.cDataStructs.UIntSparseIntV...,([O-;H0;D1:6]-[C;H0;D3;+0:5]1=[C;H0;D3;+0:7](-...,<rdkit.DataStructs.cDataStructs.UIntSparseIntV...
3,23854,Oc1ccccc1O,O=[C:2]([O-:3])/[CH:4]=[CH:5]\[CH:6]=[CH:7]/[C...,[[H+].[H+].[O:1]=[C:2]([O-:3])/[CH:4]=[CH:5]\[...,O=C([O-])/C=C\C=C/C(=O)[O-].[H+].[H+]>>O=O.OC1...,<rdkit.DataStructs.cDataStructs.UIntSparseIntV...,([OH;D1;+0:8]-[c;H0;D3;+0:7]1:[cH;D2;+0:6]:[cH...,<rdkit.DataStructs.cDataStructs.UIntSparseIntV...
4,15154,O=C([O-])c1ccc(O[C@@H]2O[C@H](CO)[C@@H](O)[C@H...,O=c1ccn([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-]...,[[O:11]=[c:12]1[cH:13][cH:14][n:15]([C@@H:16]2...,O=C([O-])C1=CC=C(O)C=C1.O=C1C=CN([C@@H]2O[C@H]...,<rdkit.DataStructs.cDataStructs.UIntSparseIntV...,([#8:2]-[C@H;D3;+0:1](-[C:3])-[O;H0;D2;+0:4]-[...,<rdkit.DataStructs.cDataStructs.UIntSparseIntV...
...,...,...,...,...,...,...,...,...
16643,49602,O=C([O-])CCCCCCC(=O)[O-],CC(C)(COP(=O)([O-])OP(=O)([O-])OC[C@H]1O[C@@H]...,[[CH3:1][C:2]([CH3:3])([CH2:4][O:5][P:6](=[O:7...,CC(C)(COP(=O)([O-])OP(=O)([O-])OC[C@H]1O[C@@H]...,<rdkit.DataStructs.cDataStructs.UIntSparseIntV...,([C:2]-[C;H0;D3;+0:1](-[O-;H0;D1:4])=[O;D1;H0:...,<rdkit.DataStructs.cDataStructs.UIntSparseIntV...
16644,48753,OCC1=C[C@H](N[C@@H]2[C@H](O)[C@@H](O)[C@H](O[C...,O=C([O-])CCC(C(=O)[O-])=[O:41].[OH:1][CH2:2][C...,[[O:35]=[C:36]([O-:37])[CH2:38][CH2:39][C:40](...,O=C([O-])CCC(=O)C(=O)[O-].O=O.OCC1=C[C@H]([NH2...,<rdkit.DataStructs.cDataStructs.UIntSparseIntV...,([C:2]=[C:3]-[C:4]-[NH;D2;+0:5]-[C:6]-[C@@H;D3...,<rdkit.DataStructs.cDataStructs.UIntSparseIntV...
16645,36164,O=C([O-])c1ccc[n+]([C@@H]2O[C@H](COP(=O)([O-])...,[O:33]=[C:34]([O-:35])[c:36]1[cH:37][cH:38][cH...,[[NH2:1][c:2]1[n:3][cH:4][n:5][c:6]2[c:7]1[n:8...,NC1=NC=NC2=C1N=CN2[C@@H]1O[C@H](COP(=O)([O-])O...,<rdkit.DataStructs.cDataStructs.UIntSparseIntV...,([#8:2]-[C@H;D3;+0:1](-[C:3])-[n+;H0;D3:5](:[c...,<rdkit.DataStructs.cDataStructs.UIntSparseIntV...
16646,40292,CC(C)(COP(=O)([O-])OP(=O)([O-])OC[C@H]1O[C@@H]...,[CH3:1][C:2]([CH3:3])([CH2:4][O:5][P:6](=[O:7]...,[[CH3:1][C:2]([CH3:3])([CH2:4][O:5][P:6](=[O:7...,CC(C)(COP(=O)([O-])OP(=O)([O-])OC[C@H]1O[C@@H]...,<rdkit.DataStructs.cDataStructs.UIntSparseIntV...,([C:4]-[S;H0;D2;+0:5]-[C;H0;D3;+0:2](-[C:1])=[...,<rdkit.DataStructs.cDataStructs.UIntSparseIntV...
16647,41641,CC(C)(COP(=O)([O-])OP(=O)([O-])OC[C@H]1O[C@@H]...,[CH3:18][C:19]([CH3:20])([CH2:21][O:22][P:23](...,[[CH3:18][C:19]([CH3:20])([CH2:21][O:22][P:23]...,CC(C)(COP(=O)([O-])OP(=O)([O-])OC[C@H]1O[C@@H]...,<rdkit.DataStructs.cDataStructs.UIntSparseIntV...,([C:4]-[S;H0;D2;+0:5]-[C;H0;D3;+0:2](-[C:1])=[...,<rdkit.DataStructs.cDataStructs.UIntSparseIntV...

In [42]:
rdenzyme_file['id'] = rdenzyme_file['id'].astype(str)


duplicate_counts = rdenzyme_file['id'].value_counts()
duplicates = set(duplicate_counts[duplicate_counts > 1].index)

# Add suffixes to duplicates
duplicate_counters = {}
new_ids = []

for _id in rdenzyme_file['id']:
    if _id in duplicates:
        count = duplicate_counters.get(_id, 0)
        new_ids.append(f"{_id}-{count}")
        duplicate_counters[_id] = count + 1
    else:
        new_ids.append(_id)

rdenzyme_file['id'] = new_ids

In [63]:
duplicate_counts

id
18391    6
27374    6
10578    6
15755    6
14211    6
        ..
22538    1
51257    1
50010    1
33853    1
41641    1
Name: count, Length: 13933, dtype: int64

In [ ]:
def add_missing_components(rhea_id=None, precursors=None, df=None, target=None, debug=False):

    matching_row = df[df['id'] == str(rhea_id)]

    # Check if matching_row is empty
    if matching_row.empty:
        if debug:
            print(f"Warning: No cofactor data found for RHEA ID {rhea_id}")
        # Return a basic reaction without cofactors
        return '.'.join(precursors) + '>>' + target
        
    cofactors_right = matching_row['missing_comp_right'].iloc[0]
    cofactors_left = matching_row['missing_comp_left'].iloc[0]

    # Build left side (from precursors)
    left_molecules = precursors
    if not pd.isna(cofactors_left):
        for cofactor in cofactors_left.split('.'):
            if cofactor not in precursors and cofactor != "nan":
                left_molecules.append(cofactor)
                
    # Build right side (from target)
    right_molecules = [target]
    if not pd.isna(cofactors_right):
        for cofactor in cofactors_right.split('.'):
            if cofactor != target and cofactor != "nan":
                    right_molecules.append(cofactor)
        
    # fully assembled reaction
    full_reaction = '.'.join(left_molecules) + '>>' + '.'.join(right_molecules)

    if debug:
        print(f"Adding missing reaction components: {full_reaction}")

    return full_reaction

In [72]:
df[df['id'] == "18391-2"]

,id,missing_comp_left,missing_comp_right
15336,18391-2,nan,O=P([O-])([O-])O[C@H]1OC[C@@H](O)[C@H](O)[C@H]...

In [87]:
for index, row in rdenzyme_file[rdenzyme_file['id'] == "18391-4"].iterrows():
    print(row.to_dict())

{'id': '18391-4', 'prod_smiles': 'O=P([O-])([O-])O[C@H]1OC[C@@H](O)[C@H](O)[C@H]1O', 'rxn_smiles': 'O=c1ccn([C@@H]2O[C@H](COP(=O)([O-])O[P:24](=[O:25])([O-:26])[O:27][C@H:28]3[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]3[OH:36])[C@@H](O)[C@H]2O)c(=O)[nH]1.O=P([O-])([O-])OP(=O)([O-])[OH:9]>>[O-:9][P:24](=[O:25])([O-:26])[O:27][C@H:28]1[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]1[OH:36]', 'atom mapped smiles-input': ['[O:10]=[c:11]1[cH:12][cH:13][n:14]([C@@H:15]2[O:16][C@H:17]([CH2:18][O:19][P:20](=[O:21])([O-:22])[O:23][P:24](=[O:25])([O-:26])[O:27][C@H:28]3[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]3[OH:36])[C@@H:37]([OH:38])[C@H:39]2[OH:40])[c:41](=[O:42])[nH:43]1.[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:6](=[O:7])([O-:8])[OH:9]>>[H+:65].[O-:8][P:24](=[O:25])([O-:26])[O:27][C@H:28]1[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]1[OH:36].[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:6](=[O:7])([O-:9])[O:23][P:20]([O:19][CH2:18][C@H:17]1[O:16][C@@H:15]([n:14]2[cH:13][cH:12][c:11](=[O:10])[nH:43][c:41]2=[O:42])[C@H:39]([OH:40])[C@@H:37]1[OH:38])(=[O:21])[O-:22]', '[O:10]=[c:11]1[cH:12][cH:13][n:14]([C@@H:15]2[O:16][C@H:17]([CH2:18][O:19][P:20](=[O:21])([O-:22])[O:23][P:24](=[O:25])([O-:26])[O:27][C@H:28]3[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]3[OH:36])[C@@H:37]([OH:38])[C@H:39]2[OH:40])[c:41](=[O:42])[nH:43]1.[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:6](=[O:7])([O-:8])[OH:9]>>[H+:65].[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:24]([O:23][P:20]([O:19][CH2:18][C@H:17]1[O:16][C@@H:15]([n:14]2[cH:13][cH:12][c:11](=[O:10])[nH:43][c:41]2=[O:42])[C@H:39]([OH:40])[C@@H:37]1[OH:38])(=[O:21])[O-:22])(=[O:25])[O-:26].[P:6](=[O:7])([O-:8])([O-:9])[O:27][C@H:28]1[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]1[OH:36]', '[O:10]=[c:11]1[cH:12][cH:13][n:14]([C@@H:15]2[O:16][C@H:17]([CH2:18][O:19][P:20](=[O:21])([O-:22])[O:23][P:24](=[O:25])([O-:26])[O:27][C@H:28]3[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]3[OH:36])[C@@H:37]([OH:38])[C@H:39]2[OH:40])[c:41](=[O:42])[nH:43]1.[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:6](=[O:7])([O-:8])[OH:9]>>[H+:65].[O-:9][P:24](=[O:25])([O-:26])[O:27][C@H:28]1[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]1[OH:36].[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:6](=[O:7])([O-:8])[O:23][P:20]([O:19][CH2:18][C@H:17]1[O:16][C@@H:15]([n:14]2[cH:13][cH:12][c:11](=[O:10])[nH:43][c:41]2=[O:42])[C@H:39]([OH:40])[C@@H:37]1[OH:38])(=[O:21])[O-:22]'], 'not atom mapped smiles-input': 'O=C1C=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])O[C@H]3OC[C@@H](O)[C@H](O)[C@H]3O)[C@@H](O)[C@H]2O)C(=O)N1.O=P([O-])([O-])OP(=O)([O-])O>>O=C1C=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OP(=O)([O-])[O-])[C@@H](O)[C@H]2O)C(=O)N1.O=P([O-])([O-])O[C@H]1OC[C@@H](O)[C@H](O)[C@H]1O.[H+]', 'prod_fp': <rdkit.DataStructs.cDataStructs.UIntSparseIntVect object at 0x00000291589142C0>, 'reaction_smarts': '([#8:2]-[P;H0;D4;+0:1](-[O-;H0;D1:5])(-[O;-;D1;H0:3])=[O;D1;H0:4])>>O-[C@@H]1-[C@@H](-C-O-P(=O)(-[O-])-O-[P;H0;D4;+0:1](-[#8:2])(-[O;-;D1;H0:3])=[O;D1;H0:4])-O-[C@@H](-n2:c:c:c(=O):[nH]:c:2=O)-[C@@H]-1-O.O=P(-[O-])(-[O-])-O-P(=O)(-[O-])-[OH;D1;+0:5]', 'rcts_ref_fp': <rdkit.DataStructs.cDataStructs.UIntSparseIntVect object at 0x000002915846A540>}

In [83]:
len(rdenzyme_file)

16648

In [ ]:
rhea_id = "55201-3"
precursors = ['C[S+](C[C@H]1O[C@H]([C@@H]([C@@H]1O)O)n(cn2)c3c2c(N)ncn3)CC[C@@H](C([O-])=O)[NH3+]']
target = 'C[C@H]1O[C@H]([C@@H]([C@@H]1O)O)n(cn2)c3c2c(N)ncn3'
add_missing_components(rhea_id=rhea_id, precursors=precursors, df=df, target=target, debug=True)

Adding missing reaction components: C[S+](C[C@H]1O[C@H]([C@@H]([C@@H]1O)O)n(cn2)c3c2c(N)ncn3)CC[C@@H](C([O-])=O)[NH3+].Nc1c(NC[C@H](O)[C@H](O)[C@H](O)CO)[nH]c(=O)[nH]c1=O.[NH3+][C@@H](Cc1ccc(O)cc1)C(=O)[O-]>>C[C@H]1O[C@H]([C@@H]([C@@H]1O)O)n(cn2)c3c2c(N)ncn3.CSCC[C@H]([NH3+])C(=O)[O-].NC1(Cc2ccc(O)cc2)C(=O)NC(=O)N/C1=N/C[C@H](O)[C@H](O)[C@H](O)CO.[H+].[NH2+]=CC(=O)[O-]

'C[S+](C[C@H]1O[C@H]([C@@H]([C@@H]1O)O)n(cn2)c3c2c(N)ncn3)CC[C@@H](C([O-])=O)[NH3+].Nc1c(NC[C@H](O)[C@H](O)[C@H](O)CO)[nH]c(=O)[nH]c1=O.[NH3+][C@@H](Cc1ccc(O)cc1)C(=O)[O-]>>C[C@H]1O[C@H]([C@@H]([C@@H]1O)O)n(cn2)c3c2c(N)ncn3.CSCC[C@H]([NH3+])C(=O)[O-].NC1(Cc2ccc(O)cc2)C(=O)NC(=O)N/C1=N/C[C@H](O)[C@H](O)[C@H](O)CO.[H+].[NH2+]=CC(=O)[O-]'

In [62]:
rdenzyme_file.to_pickle("../data/rhea_atom_mapped_for_jx_cache_modified.pkl")

In [84]:
rdenzyme_file.to_csv("../data/rhea_atom_mapped_for_jx_cache_modified.csv")

In [99]:
# Check how many rows total
print(f"Total rows in pickle: {len(rdenzyme_file)}")

for index, row in rdenzyme_file[rdenzyme_file['id'].str.startswith('18391')].iterrows():
    a = row.to_dict()
    for key,value in a.items():
        print(f"{key}: {value}")
    print("\n")

Total rows in pickle: 16648
id: 18391-0
prod_smiles: O=c1ccn([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OP(=O)([O-])[O-])[C@@H](O)[C@H]2O)c(=O)[nH]1
rxn_smiles: O=P([O-])(O[C@H]1OC[C@@H](O)[C@H](O)[C@H]1O)[O:23][P:20]([O:19][CH2:18][C@H:17]1[O:16][C@@H:15]([n:14]2[cH:13][cH:12][c:11](=[O:10])[nH:43][c:41]2=[O:42])[C@H:39]([OH:40])[C@@H:37]1[OH:38])(=[O:21])[O-:22].[O-][P:6]([O:5][P:2](=[O:1])([O-:3])[O-:4])(=[O:7])[OH:9]>>[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:6](=[O:7])([O-:9])[O:23][P:20]([O:19][CH2:18][C@H:17]1[O:16][C@@H:15]([n:14]2[cH:13][cH:12][c:11](=[O:10])[nH:43][c:41]2=[O:42])[C@H:39]([OH:40])[C@@H:37]1[OH:38])(=[O:21])[O-:22]
atom mapped smiles-input: ['[O:10]=[c:11]1[cH:12][cH:13][n:14]([C@@H:15]2[O:16][C@H:17]([CH2:18][O:19][P:20](=[O:21])([O-:22])[O:23][P:24](=[O:25])([O-:26])[O:27][C@H:28]3[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]3[OH:36])[C@@H:37]([OH:38])[C@H:39]2[OH:40])[c:41](=[O:42])[nH:43]1.[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:6](=[O:7])([O-:8])[OH:9]>>[H+:65].[O-:8][P:24](=[O:25])([O-:26])[O:27][C@H:28]1[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]1[OH:36].[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:6](=[O:7])([O-:9])[O:23][P:20]([O:19][CH2:18][C@H:17]1[O:16][C@@H:15]([n:14]2[cH:13][cH:12][c:11](=[O:10])[nH:43][c:41]2=[O:42])[C@H:39]([OH:40])[C@@H:37]1[OH:38])(=[O:21])[O-:22]', '[O:10]=[c:11]1[cH:12][cH:13][n:14]([C@@H:15]2[O:16][C@H:17]([CH2:18][O:19][P:20](=[O:21])([O-:22])[O:23][P:24](=[O:25])([O-:26])[O:27][C@H:28]3[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]3[OH:36])[C@@H:37]([OH:38])[C@H:39]2[OH:40])[c:41](=[O:42])[nH:43]1.[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:6](=[O:7])([O-:8])[OH:9]>>[H+:65].[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:24]([O:23][P:20]([O:19][CH2:18][C@H:17]1[O:16][C@@H:15]([n:14]2[cH:13][cH:12][c:11](=[O:10])[nH:43][c:41]2=[O:42])[C@H:39]([OH:40])[C@@H:37]1[OH:38])(=[O:21])[O-:22])(=[O:25])[O-:26].[P:6](=[O:7])([O-:8])([O-:9])[O:27][C@H:28]1[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]1[OH:36]', '[O:10]=[c:11]1[cH:12][cH:13][n:14]([C@@H:15]2[O:16][C@H:17]([CH2:18][O:19][P:20](=[O:21])([O-:22])[O:23][P:24](=[O:25])([O-:26])[O:27][C@H:28]3[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]3[OH:36])[C@@H:37]([OH:38])[C@H:39]2[OH:40])[c:41](=[O:42])[nH:43]1.[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:6](=[O:7])([O-:8])[OH:9]>>[H+:65].[O-:9][P:24](=[O:25])([O-:26])[O:27][C@H:28]1[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]1[OH:36].[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:6](=[O:7])([O-:8])[O:23][P:20]([O:19][CH2:18][C@H:17]1[O:16][C@@H:15]([n:14]2[cH:13][cH:12][c:11](=[O:10])[nH:43][c:41]2=[O:42])[C@H:39]([OH:40])[C@@H:37]1[OH:38])(=[O:21])[O-:22]']
not atom mapped smiles-input: O=C1C=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])O[C@H]3OC[C@@H](O)[C@H](O)[C@H]3O)[C@@H](O)[C@H]2O)C(=O)N1.O=P([O-])([O-])OP(=O)([O-])O>>O=C1C=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OP(=O)([O-])[O-])[C@@H](O)[C@H]2O)C(=O)N1.O=P([O-])([O-])O[C@H]1OC[C@@H](O)[C@H](O)[C@H]1O.[H+]
prod_fp: <rdkit.DataStructs.cDataStructs.UIntSparseIntVect object at 0x0000029158914180>
reaction_smarts: ([#15:2]-[O;H0;D2;+0:1]-[P;H0;D4;+0:4](-[#8:3])(-[O-;H0;D1:6])=[O;D1;H0:5])>>O-[C@@H]1-C-O-[C@H](-O-P(=O)(-[O-])-[O;H0;D2;+0:1]-[#15:2])-[C@H](-O)-[C@H]-1-O.[#8:3]-[P;H0;D4;+0:4](-[O-])(=[O;D1;H0:5])-[OH;D1;+0:6]
rcts_ref_fp: <rdkit.DataStructs.cDataStructs.UIntSparseIntVect object at 0x000002915846A400>


id: 18391-1
prod_smiles: O=c1ccn([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OP(=O)([O-])[O-])[C@@H](O)[C@H]2O)c(=O)[nH]1
rxn_smiles: O=P([O-])(O[C@H]1OC[C@@H](O)[C@H](O)[C@H]1O)[O:23][P:20]([O:19][CH2:18][C@H:17]1[O:16][C@@H:15]([n:14]2[cH:13][cH:12][c:11](=[O:10])[nH:43][c:41]2=[O:42])[C@H:39]([OH:40])[C@@H:37]1[OH:38])(=[O:21])[O-:22].O[P:6]([O:5][P:2](=[O:1])([O-:3])[O-:4])(=[O:7])[O-:8]>>[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:6](=[O:7])([O-:8])[O:23][P:20]([O:19][CH2:18][C@H:17]1[O:16][C@@H:15]([n:14]2[cH:13][cH:12][c:11](=[O:10])[nH:43][c:41]2=[O:42])[C@H:39]([OH:40])[C@@H:37]1[OH:38])(=[O:21])[O-:22]
atom mapped smiles-input: ['[O:10]=[c:11]1[cH:12][cH:13][n:14]([C@@H:15]2[O:16][C@H:17]([CH2:18][O:19][P:20](=[O:21])([O-:22])[O:23][P:24](=[O:25])([O-:26])[O:27][C@H:28]3[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]3[OH:36])[C@@H:37]([OH:38])[C@H:39]2[OH:40])[c:41](=[O:42])[nH:43]1.[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:6](=[O:7])([O-:8])[OH:9]>>[H+:65].[O-:8][P:24](=[O:25])([O-:26])[O:27][C@H:28]1[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]1[OH:36].[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:6](=[O:7])([O-:9])[O:23][P:20]([O:19][CH2:18][C@H:17]1[O:16][C@@H:15]([n:14]2[cH:13][cH:12][c:11](=[O:10])[nH:43][c:41]2=[O:42])[C@H:39]([OH:40])[C@@H:37]1[OH:38])(=[O:21])[O-:22]', '[O:10]=[c:11]1[cH:12][cH:13][n:14]([C@@H:15]2[O:16][C@H:17]([CH2:18][O:19][P:20](=[O:21])([O-:22])[O:23][P:24](=[O:25])([O-:26])[O:27][C@H:28]3[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]3[OH:36])[C@@H:37]([OH:38])[C@H:39]2[OH:40])[c:41](=[O:42])[nH:43]1.[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:6](=[O:7])([O-:8])[OH:9]>>[H+:65].[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:24]([O:23][P:20]([O:19][CH2:18][C@H:17]1[O:16][C@@H:15]([n:14]2[cH:13][cH:12][c:11](=[O:10])[nH:43][c:41]2=[O:42])[C@H:39]([OH:40])[C@@H:37]1[OH:38])(=[O:21])[O-:22])(=[O:25])[O-:26].[P:6](=[O:7])([O-:8])([O-:9])[O:27][C@H:28]1[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]1[OH:36]', '[O:10]=[c:11]1[cH:12][cH:13][n:14]([C@@H:15]2[O:16][C@H:17]([CH2:18][O:19][P:20](=[O:21])([O-:22])[O:23][P:24](=[O:25])([O-:26])[O:27][C@H:28]3[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]3[OH:36])[C@@H:37]([OH:38])[C@H:39]2[OH:40])[c:41](=[O:42])[nH:43]1.[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:6](=[O:7])([O-:8])[OH:9]>>[H+:65].[O-:9][P:24](=[O:25])([O-:26])[O:27][C@H:28]1[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]1[OH:36].[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:6](=[O:7])([O-:8])[O:23][P:20]([O:19][CH2:18][C@H:17]1[O:16][C@@H:15]([n:14]2[cH:13][cH:12][c:11](=[O:10])[nH:43][c:41]2=[O:42])[C@H:39]([OH:40])[C@@H:37]1[OH:38])(=[O:21])[O-:22]']
not atom mapped smiles-input: O=C1C=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])O[C@H]3OC[C@@H](O)[C@H](O)[C@H]3O)[C@@H](O)[C@H]2O)C(=O)N1.O=P([O-])([O-])OP(=O)([O-])O>>O=C1C=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OP(=O)([O-])[O-])[C@@H](O)[C@H]2O)C(=O)N1.O=P([O-])([O-])O[C@H]1OC[C@@H](O)[C@H](O)[C@H]1O.[H+]
prod_fp: <rdkit.DataStructs.cDataStructs.UIntSparseIntVect object at 0x00000291589141D0>
reaction_smarts: ([#15:2]-[O;H0;D2;+0:1]-[P;H0;D4;+0:3](-[#8:4])(-[O;-;D1;H0:5])=[O;D1;H0:6])>>O-[C@@H]1-C-O-[C@H](-O-P(=O)(-[O-])-[O;H0;D2;+0:1]-[#15:2])-[C@H](-O)-[C@H]-1-O.O-[P;H0;D4;+0:3](-[#8:4])(-[O;-;D1;H0:5])=[O;D1;H0:6]
rcts_ref_fp: <rdkit.DataStructs.cDataStructs.UIntSparseIntVect object at 0x000002915846A450>


id: 18391-2
prod_smiles: O=c1ccn([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OP(=O)([O-])[O-])[C@@H](O)[C@H]2O)c(=O)[nH]1
rxn_smiles: O[C@H]1[C@@H](O[P:24]([O:23][P:20]([O:19][CH2:18][C@H:17]2[O:16][C@@H:15]([n:14]3[cH:13][cH:12][c:11](=[O:10])[nH:43][c:41]3=[O:42])[C@H:39]([OH:40])[C@@H:37]2[OH:38])(=[O:21])[O-:22])(=[O:25])[O-:26])OC[C@@H](O)[C@@H]1O.O=P([O-])(O)[O:5][P:2](=[O:1])([O-:3])[O-:4]>>[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:24]([O:23][P:20]([O:19][CH2:18][C@H:17]1[O:16][C@@H:15]([n:14]2[cH:13][cH:12][c:11](=[O:10])[nH:43][c:41]2=[O:42])[C@H:39]([OH:40])[C@@H:37]1[OH:38])(=[O:21])[O-:22])(=[O:25])[O-:26]
atom mapped smiles-input: ['[O:10]=[c:11]1[cH:12][cH:13][n:14]([C@@H:15]2[O:16][C@H:17]([CH2:18][O:19][P:20](=[O:21])([O-:22])[O:23][P:24](=[O:25])([O-:26])[O:27][C@H:28]3[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]3[OH:36])[C@@H:37]([OH:38])[C@H:39]2[OH:40])[c:41](=[O:42])[nH:43]1.[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:6](=[O:7])([O-:8])[OH:9]>>[H+:65].[O-:8][P:24](=[O:25])([O-:26])[O:27][C@H:28]1[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]1[OH:36].[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:6](=[O:7])([O-:9])[O:23][P:20]([O:19][CH2:18][C@H:17]1[O:16][C@@H:15]([n:14]2[cH:13][cH:12][c:11](=[O:10])[nH:43][c:41]2=[O:42])[C@H:39]([OH:40])[C@@H:37]1[OH:38])(=[O:21])[O-:22]', '[O:10]=[c:11]1[cH:12][cH:13][n:14]([C@@H:15]2[O:16][C@H:17]([CH2:18][O:19][P:20](=[O:21])([O-:22])[O:23][P:24](=[O:25])([O-:26])[O:27][C@H:28]3[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]3[OH:36])[C@@H:37]([OH:38])[C@H:39]2[OH:40])[c:41](=[O:42])[nH:43]1.[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:6](=[O:7])([O-:8])[OH:9]>>[H+:65].[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:24]([O:23][P:20]([O:19][CH2:18][C@H:17]1[O:16][C@@H:15]([n:14]2[cH:13][cH:12][c:11](=[O:10])[nH:43][c:41]2=[O:42])[C@H:39]([OH:40])[C@@H:37]1[OH:38])(=[O:21])[O-:22])(=[O:25])[O-:26].[P:6](=[O:7])([O-:8])([O-:9])[O:27][C@H:28]1[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]1[OH:36]', '[O:10]=[c:11]1[cH:12][cH:13][n:14]([C@@H:15]2[O:16][C@H:17]([CH2:18][O:19][P:20](=[O:21])([O-:22])[O:23][P:24](=[O:25])([O-:26])[O:27][C@H:28]3[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]3[OH:36])[C@@H:37]([OH:38])[C@H:39]2[OH:40])[c:41](=[O:42])[nH:43]1.[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:6](=[O:7])([O-:8])[OH:9]>>[H+:65].[O-:9][P:24](=[O:25])([O-:26])[O:27][C@H:28]1[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]1[OH:36].[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:6](=[O:7])([O-:8])[O:23][P:20]([O:19][CH2:18][C@H:17]1[O:16][C@@H:15]([n:14]2[cH:13][cH:12][c:11](=[O:10])[nH:43][c:41]2=[O:42])[C@H:39]([OH:40])[C@@H:37]1[OH:38])(=[O:21])[O-:22]']
not atom mapped smiles-input: O=C1C=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])O[C@H]3OC[C@@H](O)[C@H](O)[C@H]3O)[C@@H](O)[C@H]2O)C(=O)N1.O=P([O-])([O-])OP(=O)([O-])O>>O=C1C=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OP(=O)([O-])[O-])[C@@H](O)[C@H]2O)C(=O)N1.O=P([O-])([O-])O[C@H]1OC[C@@H](O)[C@H](O)[C@H]1O.[H+]
prod_fp: <rdkit.DataStructs.cDataStructs.UIntSparseIntVect object at 0x0000029158914220>
reaction_smarts: ([#15:2]-[O;H0;D2;+0:1]-[P;H0;D4;+0:3](-[#8:4])(-[O;-;D1;H0:5])=[O;D1;H0:6])>>O-P(=O)(-[O-])-[O;H0;D2;+0:1]-[#15:2].O-[C@@H]1-C-O-[C@H](-O-[P;H0;D4;+0:3](-[#8:4])(-[O;-;D1;H0:5])=[O;D1;H0:6])-[C@H](-O)-[C@H]-1-O
rcts_ref_fp: <rdkit.DataStructs.cDataStructs.UIntSparseIntVect object at 0x000002915846A4A0>


id: 18391-3
prod_smiles: O=P([O-])([O-])O[C@H]1OC[C@@H](O)[C@H](O)[C@H]1O
rxn_smiles: O=c1ccn([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])[O:27][C@H:28]3[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]3[OH:36])[C@@H](O)[C@H]2O)c(=O)[nH]1.O=P([O-])([O-])O[P:6](=[O:7])([O-:8])[OH:9]>>[P:6](=[O:7])([O-:8])([O-:9])[O:27][C@H:28]1[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]1[OH:36]
atom mapped smiles-input: ['[O:10]=[c:11]1[cH:12][cH:13][n:14]([C@@H:15]2[O:16][C@H:17]([CH2:18][O:19][P:20](=[O:21])([O-:22])[O:23][P:24](=[O:25])([O-:26])[O:27][C@H:28]3[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]3[OH:36])[C@@H:37]([OH:38])[C@H:39]2[OH:40])[c:41](=[O:42])[nH:43]1.[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:6](=[O:7])([O-:8])[OH:9]>>[H+:65].[O-:8][P:24](=[O:25])([O-:26])[O:27][C@H:28]1[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]1[OH:36].[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:6](=[O:7])([O-:9])[O:23][P:20]([O:19][CH2:18][C@H:17]1[O:16][C@@H:15]([n:14]2[cH:13][cH:12][c:11](=[O:10])[nH:43][c:41]2=[O:42])[C@H:39]([OH:40])[C@@H:37]1[OH:38])(=[O:21])[O-:22]', '[O:10]=[c:11]1[cH:12][cH:13][n:14]([C@@H:15]2[O:16][C@H:17]([CH2:18][O:19][P:20](=[O:21])([O-:22])[O:23][P:24](=[O:25])([O-:26])[O:27][C@H:28]3[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]3[OH:36])[C@@H:37]([OH:38])[C@H:39]2[OH:40])[c:41](=[O:42])[nH:43]1.[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:6](=[O:7])([O-:8])[OH:9]>>[H+:65].[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:24]([O:23][P:20]([O:19][CH2:18][C@H:17]1[O:16][C@@H:15]([n:14]2[cH:13][cH:12][c:11](=[O:10])[nH:43][c:41]2=[O:42])[C@H:39]([OH:40])[C@@H:37]1[OH:38])(=[O:21])[O-:22])(=[O:25])[O-:26].[P:6](=[O:7])([O-:8])([O-:9])[O:27][C@H:28]1[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]1[OH:36]', '[O:10]=[c:11]1[cH:12][cH:13][n:14]([C@@H:15]2[O:16][C@H:17]([CH2:18][O:19][P:20](=[O:21])([O-:22])[O:23][P:24](=[O:25])([O-:26])[O:27][C@H:28]3[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]3[OH:36])[C@@H:37]([OH:38])[C@H:39]2[OH:40])[c:41](=[O:42])[nH:43]1.[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:6](=[O:7])([O-:8])[OH:9]>>[H+:65].[O-:9][P:24](=[O:25])([O-:26])[O:27][C@H:28]1[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]1[OH:36].[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:6](=[O:7])([O-:8])[O:23][P:20]([O:19][CH2:18][C@H:17]1[O:16][C@@H:15]([n:14]2[cH:13][cH:12][c:11](=[O:10])[nH:43][c:41]2=[O:42])[C@H:39]([OH:40])[C@@H:37]1[OH:38])(=[O:21])[O-:22]']
not atom mapped smiles-input: O=C1C=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])O[C@H]3OC[C@@H](O)[C@H](O)[C@H]3O)[C@@H](O)[C@H]2O)C(=O)N1.O=P([O-])([O-])OP(=O)([O-])O>>O=C1C=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OP(=O)([O-])[O-])[C@@H](O)[C@H]2O)C(=O)N1.O=P([O-])([O-])O[C@H]1OC[C@@H](O)[C@H](O)[C@H]1O.[H+]
prod_fp: <rdkit.DataStructs.cDataStructs.UIntSparseIntVect object at 0x0000029158914270>
reaction_smarts: ([#8:3]-[C:2]-[O;H0;D2;+0:1]-[P;H0;D4;+0:4](-[O-;H0;D1:7])(-[O;-;D1;H0:5])=[O;D1;H0:6])>>O-[C@@H]1-[C@@H](-C-O-P(=O)(-[O-])-O-P(=O)(-[O-])-[O;H0;D2;+0:1]-[C:2]-[#8:3])-O-[C@@H](-n2:c:c:c(=O):[nH]:c:2=O)-[C@@H]-1-O.O=P(-[O-])(-[O-])-O-[P;H0;D4;+0:4](-[O;-;D1;H0:5])(=[O;D1;H0:6])-[OH;D1;+0:7]
rcts_ref_fp: <rdkit.DataStructs.cDataStructs.UIntSparseIntVect object at 0x000002915846A4F0>


id: 18391-4
prod_smiles: O=P([O-])([O-])O[C@H]1OC[C@@H](O)[C@H](O)[C@H]1O
rxn_smiles: O=c1ccn([C@@H]2O[C@H](COP(=O)([O-])O[P:24](=[O:25])([O-:26])[O:27][C@H:28]3[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]3[OH:36])[C@@H](O)[C@H]2O)c(=O)[nH]1.O=P([O-])([O-])OP(=O)([O-])[OH:9]>>[O-:9][P:24](=[O:25])([O-:26])[O:27][C@H:28]1[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]1[OH:36]
atom mapped smiles-input: ['[O:10]=[c:11]1[cH:12][cH:13][n:14]([C@@H:15]2[O:16][C@H:17]([CH2:18][O:19][P:20](=[O:21])([O-:22])[O:23][P:24](=[O:25])([O-:26])[O:27][C@H:28]3[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]3[OH:36])[C@@H:37]([OH:38])[C@H:39]2[OH:40])[c:41](=[O:42])[nH:43]1.[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:6](=[O:7])([O-:8])[OH:9]>>[H+:65].[O-:8][P:24](=[O:25])([O-:26])[O:27][C@H:28]1[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]1[OH:36].[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:6](=[O:7])([O-:9])[O:23][P:20]([O:19][CH2:18][C@H:17]1[O:16][C@@H:15]([n:14]2[cH:13][cH:12][c:11](=[O:10])[nH:43][c:41]2=[O:42])[C@H:39]([OH:40])[C@@H:37]1[OH:38])(=[O:21])[O-:22]', '[O:10]=[c:11]1[cH:12][cH:13][n:14]([C@@H:15]2[O:16][C@H:17]([CH2:18][O:19][P:20](=[O:21])([O-:22])[O:23][P:24](=[O:25])([O-:26])[O:27][C@H:28]3[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]3[OH:36])[C@@H:37]([OH:38])[C@H:39]2[OH:40])[c:41](=[O:42])[nH:43]1.[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:6](=[O:7])([O-:8])[OH:9]>>[H+:65].[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:24]([O:23][P:20]([O:19][CH2:18][C@H:17]1[O:16][C@@H:15]([n:14]2[cH:13][cH:12][c:11](=[O:10])[nH:43][c:41]2=[O:42])[C@H:39]([OH:40])[C@@H:37]1[OH:38])(=[O:21])[O-:22])(=[O:25])[O-:26].[P:6](=[O:7])([O-:8])([O-:9])[O:27][C@H:28]1[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]1[OH:36]', '[O:10]=[c:11]1[cH:12][cH:13][n:14]([C@@H:15]2[O:16][C@H:17]([CH2:18][O:19][P:20](=[O:21])([O-:22])[O:23][P:24](=[O:25])([O-:26])[O:27][C@H:28]3[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]3[OH:36])[C@@H:37]([OH:38])[C@H:39]2[OH:40])[c:41](=[O:42])[nH:43]1.[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:6](=[O:7])([O-:8])[OH:9]>>[H+:65].[O-:9][P:24](=[O:25])([O-:26])[O:27][C@H:28]1[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]1[OH:36].[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:6](=[O:7])([O-:8])[O:23][P:20]([O:19][CH2:18][C@H:17]1[O:16][C@@H:15]([n:14]2[cH:13][cH:12][c:11](=[O:10])[nH:43][c:41]2=[O:42])[C@H:39]([OH:40])[C@@H:37]1[OH:38])(=[O:21])[O-:22]']
not atom mapped smiles-input: O=C1C=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])O[C@H]3OC[C@@H](O)[C@H](O)[C@H]3O)[C@@H](O)[C@H]2O)C(=O)N1.O=P([O-])([O-])OP(=O)([O-])O>>O=C1C=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OP(=O)([O-])[O-])[C@@H](O)[C@H]2O)C(=O)N1.O=P([O-])([O-])O[C@H]1OC[C@@H](O)[C@H](O)[C@H]1O.[H+]
prod_fp: <rdkit.DataStructs.cDataStructs.UIntSparseIntVect object at 0x00000291589142C0>
reaction_smarts: ([#8:2]-[P;H0;D4;+0:1](-[O-;H0;D1:5])(-[O;-;D1;H0:3])=[O;D1;H0:4])>>O-[C@@H]1-[C@@H](-C-O-P(=O)(-[O-])-O-[P;H0;D4;+0:1](-[#8:2])(-[O;-;D1;H0:3])=[O;D1;H0:4])-O-[C@@H](-n2:c:c:c(=O):[nH]:c:2=O)-[C@@H]-1-O.O=P(-[O-])(-[O-])-O-P(=O)(-[O-])-[OH;D1;+0:5]
rcts_ref_fp: <rdkit.DataStructs.cDataStructs.UIntSparseIntVect object at 0x000002915846A540>


id: 18391-5
prod_smiles: O=P([O-])([O-])O[C@H]1OC[C@@H](O)[C@H](O)[C@H]1O
rxn_smiles: O=c1ccn([C@@H]2O[C@H](COP(=O)([O-])O[P:24](=[O:25])([O-:26])[O:27][C@H:28]3[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]3[OH:36])[C@@H](O)[C@H]2O)c(=O)[nH]1.O=P([O-])([O-])OP(=O)(O)[O-:8]>>[O-:8][P:24](=[O:25])([O-:26])[O:27][C@H:28]1[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]1[OH:36]
atom mapped smiles-input: ['[O:10]=[c:11]1[cH:12][cH:13][n:14]([C@@H:15]2[O:16][C@H:17]([CH2:18][O:19][P:20](=[O:21])([O-:22])[O:23][P:24](=[O:25])([O-:26])[O:27][C@H:28]3[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]3[OH:36])[C@@H:37]([OH:38])[C@H:39]2[OH:40])[c:41](=[O:42])[nH:43]1.[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:6](=[O:7])([O-:8])[OH:9]>>[H+:65].[O-:8][P:24](=[O:25])([O-:26])[O:27][C@H:28]1[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]1[OH:36].[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:6](=[O:7])([O-:9])[O:23][P:20]([O:19][CH2:18][C@H:17]1[O:16][C@@H:15]([n:14]2[cH:13][cH:12][c:11](=[O:10])[nH:43][c:41]2=[O:42])[C@H:39]([OH:40])[C@@H:37]1[OH:38])(=[O:21])[O-:22]', '[O:10]=[c:11]1[cH:12][cH:13][n:14]([C@@H:15]2[O:16][C@H:17]([CH2:18][O:19][P:20](=[O:21])([O-:22])[O:23][P:24](=[O:25])([O-:26])[O:27][C@H:28]3[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]3[OH:36])[C@@H:37]([OH:38])[C@H:39]2[OH:40])[c:41](=[O:42])[nH:43]1.[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:6](=[O:7])([O-:8])[OH:9]>>[H+:65].[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:24]([O:23][P:20]([O:19][CH2:18][C@H:17]1[O:16][C@@H:15]([n:14]2[cH:13][cH:12][c:11](=[O:10])[nH:43][c:41]2=[O:42])[C@H:39]([OH:40])[C@@H:37]1[OH:38])(=[O:21])[O-:22])(=[O:25])[O-:26].[P:6](=[O:7])([O-:8])([O-:9])[O:27][C@H:28]1[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]1[OH:36]', '[O:10]=[c:11]1[cH:12][cH:13][n:14]([C@@H:15]2[O:16][C@H:17]([CH2:18][O:19][P:20](=[O:21])([O-:22])[O:23][P:24](=[O:25])([O-:26])[O:27][C@H:28]3[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]3[OH:36])[C@@H:37]([OH:38])[C@H:39]2[OH:40])[c:41](=[O:42])[nH:43]1.[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:6](=[O:7])([O-:8])[OH:9]>>[H+:65].[O-:9][P:24](=[O:25])([O-:26])[O:27][C@H:28]1[O:29][CH2:30][C@@H:31]([OH:32])[C@H:33]([OH:34])[C@H:35]1[OH:36].[O:1]=[P:2]([O-:3])([O-:4])[O:5][P:6](=[O:7])([O-:8])[O:23][P:20]([O:19][CH2:18][C@H:17]1[O:16][C@@H:15]([n:14]2[cH:13][cH:12][c:11](=[O:10])[nH:43][c:41]2=[O:42])[C@H:39]([OH:40])[C@@H:37]1[OH:38])(=[O:21])[O-:22]']
not atom mapped smiles-input: O=C1C=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])O[C@H]3OC[C@@H](O)[C@H](O)[C@H]3O)[C@@H](O)[C@H]2O)C(=O)N1.O=P([O-])([O-])OP(=O)([O-])O>>O=C1C=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OP(=O)([O-])[O-])[C@@H](O)[C@H]2O)C(=O)N1.O=P([O-])([O-])O[C@H]1OC[C@@H](O)[C@H](O)[C@H]1O.[H+]
prod_fp: <rdkit.DataStructs.cDataStructs.UIntSparseIntVect object at 0x0000029158914310>
reaction_smarts: ([#8:3]-[P;H0;D4;+0:2](-[O-;H0;D1:1])(-[O;-;D1;H0:4])=[O;D1;H0:5])>>O-P(=O)(-[O-;H0;D1:1])-O-P(=O)(-[O-])-[O-].O-[C@@H]1-[C@@H](-C-O-P(=O)(-[O-])-O-[P;H0;D4;+0:2](-[#8:3])(-[O;-;D1;H0:4])=[O;D1;H0:5])-O-[C@@H](-n2:c:c:c(=O):[nH]:c:2=O)-[C@@H]-1-O
rcts_ref_fp: <rdkit.DataStructs.cDataStructs.UIntSparseIntVect object at 0x000002915846A590>